{% set version = "2.1.3" %}

package:
  name: gdal
  version: {{ version }}

source:
  url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.gz
  sha256: ae6a0a0dc6eb45a981a46db27e3dfe16c644fcf04732557e2cb315776974074a
  patches:
    - clang.patch  # [osx]
    - prepend-dll.patch  # [win]
    # Fixes compilation problems with JPEG.
    # https://lists.osgeo.org/pipermail/gdal-dev/2016-January/043443.html
    - disable_jpeg12.patch  # [win]
    - windowshdf5.patch  # [win]
    - multiprocessor.patch  # [win]
    - install_scripts.patch

build:
  number: 7
  features:
    - vc9  # [win and py27]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python
    # Must be 3.0.8
    # see https://github.com/conda-forge/gdal-feedstock/issues/131
    - swig 3.0.8
    - sed  # [osx]
    - setuptools
    - cmake  # [win]
    - curl >=7.54.1,<8
    - expat 2.1.*
    - freexl
    - geos 3.6.2
    - giflib 5.1.*  # [not win]
    - hdf4
    - hdf5 1.10.1
    - jpeg 9*
    - json-c  # [not win]
    - kealib
    - libdap4 3.18.*  # [not win]
    - libnetcdf 4.4.*
    - libpng >=1.6.22,<1.6.31
    - libspatialite
    - libtiff 4.0.*
    - numpy 1.11.*  # [win and py36]
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - openjpeg 2.1.0
    - postgresql
    - proj4 4.9.3
    - sqlite 3.13.*
    - xerces-c 3.2.0
    - zlib 1.2.11  # [not win]
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]
  run:
    - python
    - curl >=7.54.1,<8
    - expat 2.1.*
    - freexl
    - geos 3.6.2
    - giflib 5.1.*  # [not win]
    - hdf4
    - hdf5 1.10.1
    - jpeg 9*
    - json-c  # [not win]
    - kealib
    - libdap4 3.18.*  # [not win]
    - libnetcdf 4.4.*
    - libpng >=1.6.22,<1.6.31
    - libpq
    - libspatialite
    - libtiff 4.0.*
    - numpy >=1.11  # [win and py36]
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - openjpeg >=2.1,<2.3.0
    - proj4 4.9.3
    - sqlite 3.13.*
    - xerces-c 3.2.0
    - zlib 1.2.11  # [not win]
    - pcre
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]

test:
  files:
    - test_data
    - extra_tests.py
  imports:
    - osr
    - gdal
    - gdalconst
    - osgeo
    - osgeo.ogr
    - osgeo.gdal
    - osgeo._gdal
    - osgeo._gdalconst
    - osgeo._ogr
    - osgeo._osr
  commands:
    - gdal_grid --version
    - gdal_rasterize --version
    - gdal_translate --version
    - gdaladdo --version
    - gdalenhance --version
    - gdalwarp --version
    - gdalinfo --formats
    - gdalinfo http://thredds.nersc.no/thredds/dodsC/greenpath/Model/topaz  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.gdal.org/
  license: MIT
  license_file: LICENSE.TXT
  summary: 'The Geospatial Data Abstraction Library (GDAL).'

extra:
  recipe-maintainers:
    - ocefpaf
    - kmuehlbauer
    - gillins
