{% set version = "2.1.4" %}

package:
  name: gdal
  version: {{ version }}

source:
  url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.gz
  sha256: 79aa6331008af7c1d36d30e4a7dae92b2b8a3512a6084b672a2b2659731e6529
  patches:
    - clang.patch  # [osx]
    - prepend-dll.patch  # [win]
    - install_scripts.patch

build:
  number: 2
  skip: True  # [win]
  features:
    - vc9  # [win and py27]
    - vc14  # [win and (py35 and py36)]

requirements:
  build:
    - python
    - swig
    - sed  # [osx]
    - setuptools
    - cmake  # [win]
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - libgdal {{ version }}
    - openjpeg 2.1.*
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 and py36)]
  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    - libgdal {{ version }}
    - openjpeg 2.1.*
    - pcre
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 and py36)]

test:
  files:
    - extra_tests.py
    - test_data/sites.dbf
    - test_data/sites.sbn
    - test_data/sites.sbx
    - test_data/sites.shp
    - test_data/sites.shx
  imports:
    - osr
    - gdal
    - gdalconst
    - osgeo
    - osgeo.ogr
    - osgeo.gdal
    - osgeo._gdal
    - osgeo._gdalconst
    - osgeo._ogr
    - osgeo._osr
  commands:
    - gdal_grid --version
    - gdal_rasterize --version
    - gdal_translate --version
    - gdaladdo --version
    - gdalenhance --version
    - gdalwarp --version
    - gdalinfo --formats
    - gdalinfo http://thredds.nersc.no/thredds/dodsC/greenpath/Model/topaz  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.gdal.org/
  license: MIT
  license_file: LICENSE.TXT
  summary: 'Python wrapper for the Geospatial Data Abstraction Library (GDAL)'

extra:
  recipe-maintainers:
    - ocefpaf
    - kmuehlbauer
    - gillins
